databases:
  - name: sicea-db
    databaseName: siceadb
    user: siceauser
    plan: free

services:
  # Backend Django
  - type: web
    name: sicea-backend
    runtime: python
    plan: free
    buildCommand: "cd backend && chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && gunicorn SICEAproject.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: sicea-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: sicea-db
          property: host
      - key: DB_NAME
        value: siceadb
      - key: DB_USER
        value: siceauser
      - key: DB_PASSWORD
        fromDatabase:
          name: sicea-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: sicea-db
          property: port
      - key: ALLOWED_HOSTS
        value: "*"

  # Frontend React
  - type: web
    name: sicea-frontend
    runtime: static
    buildCommand: "cd frontend/sicea && npm install && npm run build"
    staticPublishPath: frontend/sicea/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
