services:
  # Base de datos PostgreSQL
  - type: pserv
    name: sicea-db
    plan: free

  # Backend Django
  - type: web
    name: sicea-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn SICEAproject.wsgi:application --bind 0.0.0.0:$PORT"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DB_HOST
        fromService:
          type: pserv
          name: sicea-db
          property: host
      - key: DB_NAME
        value: siceadb
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: sicea-db
          envVarKey: POSTGRES_PASSWORD
      - key: DB_PORT
        fromService:
          type: pserv
          name: sicea-db
          property: port
      - key: ALLOWED_HOSTS
        value: "*"

  # Frontend React
  - type: web
    name: sicea-frontend
    env: static
    plan: free
    buildCommand: "cd frontend/sicea && npm install && npm run build"
    staticPublishPath: frontend/sicea/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
